export const API_URL = 'https://api.weekday.technology/adhoc/getSampleJdJSON';

export const experienceOptions = [
  { value: '0', label: '0' },
  { value: '1', label: '1' },
  { value: '2', label: '2' },
  { value: '3', label: '3' },
  { value: '4', label: '4' },
  { value: '5', label: '5' },
  { value: '6', label: '6' },
  { value: '7', label: '7' },
  { value: '8', label: '8' },
  { value: '9', label: '9' },
  { value: '10', label: '10' },
];

export const remoteOptions = [
  { value: 'remote', label: 'Remote' },
  { value: 'on-site', label: 'On-site' },
];

export const roleOptions = [
  { value: 'frontend-developer', label: 'Frontend Developer' },
  { value: 'backend-developer', label: 'Backend Developer' },
  { value: 'full-stack-developer', label: 'Full Stack Developer' },
];

export const minBasePayOptions = [
  { value: '1000', label: '$ 1k' },
  { value: '5000', label: '$ 5k' },
  { value: '10000', label: '$ 10k' },
  { value: '20000', label: '$ 20k' },
  { value: '40000', label: '$ 40k' },
  { value: '60000', label: '$ 60k' },
  { value: '80000', label: '$ 80k' },
  { value: '100000', label: '$ 100k' },
];

export const data = [
  {
    jdUid: 'cfff35ac-053c-11ef-83d3-06301d0a7178-92010',
    jdLink: 'https://weekday.works',
    jobDetailsFromCompany:
      "This is a sample job and you must have displayed it to understand that its not just some random lorem ipsum text but something which was manually written. Oh well, if random text is what you were looking for then here it is: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages and now in this assignment.",
    maxJdSalary: 61,
    minJdSalary: null,
    salaryCurrencyCode: 'USD',
    location: 'delhi ncr',
    minExp: 3,
    maxExp: 6,
    jobRole: 'frontend',
    companyName: 'Dropbox',
    logoUrl: 'https://logo.clearbit.com/dropbox.com',
  },
  {
    jdUid: 'cfff35ba-053c-11ef-83d3-06301d0a7178-92012',
    jdLink: 'https://weekday.works',
    jobDetailsFromCompany:
      "This is a sample job and you must have displayed it to understand that its not just some random lorem ipsum text but something which was manually written. Oh well, if random text is what you were looking for then here it is: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages and now in this assignment.",
    maxJdSalary: 103,
    minJdSalary: 100,
    salaryCurrencyCode: 'USD',
    location: 'mumbai',
    minExp: null,
    maxExp: null,
    jobRole: 'ios',
    companyName: 'LG',
    logoUrl: 'https://logo.clearbit.com/lg.com',
  },
  {
    jdUid: 'cfff35d4-053c-11ef-83d3-06301d0a7178-92016',
    jdLink: 'https://weekday.works',
    jobDetailsFromCompany:
      "This is a sample job and you must have displayed it to understand that its not just some random lorem ipsum text but something which was manually written. Oh well, if random text is what you were looking for then here it is: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages and now in this assignment.",
    maxJdSalary: 28,
    minJdSalary: 26,
    salaryCurrencyCode: 'USD',
    location: 'remote',
    minExp: 2,
    maxExp: 11,
    jobRole: 'android',
    companyName: 'Sony',
    logoUrl: 'https://logo.clearbit.com/sony.com',
  },
  {
    jdUid: 'cfff35e1-053c-11ef-83d3-06301d0a7178-92018',
    jdLink: 'https://weekday.works',
    jobDetailsFromCompany:
      "This is a sample job and you must have displayed it to understand that its not just some random lorem ipsum text but something which was manually written. Oh well, if random text is what you were looking for then here it is: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages and now in this assignment.",
    maxJdSalary: 45,
    minJdSalary: 35,
    salaryCurrencyCode: 'USD',
    location: 'chennai',
    minExp: 5,
    maxExp: 6,
    jobRole: 'tech lead',
    companyName: 'Adobe Systems',
    logoUrl: 'https://logo.clearbit.com/adobe.com',
  },
  {
    jdUid: 'cfff35ed-053c-11ef-83d3-06301d0a7178-92020',
    jdLink: 'https://weekday.works',
    jobDetailsFromCompany:
      "This is a sample job and you must have displayed it to understand that its not just some random lorem ipsum text but something which was manually written. Oh well, if random text is what you were looking for then here it is: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages and now in this assignment.",
    maxJdSalary: 48,
    minJdSalary: 26,
    salaryCurrencyCode: 'USD',
    location: 'delhi ncr',
    minExp: 1,
    maxExp: 8,
    jobRole: 'frontend',
    companyName: 'HP',
    logoUrl: 'https://logo.clearbit.com/hp.com',
  },
  {
    jdUid: 'cfff35fb-053c-11ef-83d3-06301d0a7178-92022',
    jdLink: 'https://weekday.works',
    jobDetailsFromCompany:
      "This is a sample job and you must have displayed it to understand that its not just some random lorem ipsum text but something which was manually written. Oh well, if random text is what you were looking for then here it is: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages and now in this assignment.",
    maxJdSalary: 19,
    minJdSalary: 15,
    salaryCurrencyCode: 'USD',
    location: 'mumbai',
    minExp: 8,
    maxExp: 9,
    jobRole: 'ios',
    companyName: 'eBay',
    logoUrl: 'https://logo.clearbit.com/ebay.com',
  },
  {
    jdUid: 'cfff3608-053c-11ef-83d3-06301d0a7178-92024',
    jdLink: 'https://weekday.works',
    jobDetailsFromCompany:
      "This is a sample job and you must have displayed it to understand that its not just some random lorem ipsum text but something which was manually written. Oh well, if random text is what you were looking for then here it is: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages and now in this assignment.",
    maxJdSalary: 78,
    minJdSalary: 64,
    salaryCurrencyCode: 'USD',
    location: 'bangalore',
    minExp: 7,
    maxExp: 15,
    jobRole: 'backend',
    companyName: 'Tencent',
    logoUrl: 'https://logo.clearbit.com/tencent.com',
  },
  {
    jdUid: 'cfff3614-053c-11ef-83d3-06301d0a7178-92026',
    jdLink: 'https://weekday.works',
    jobDetailsFromCompany:
      "This is a sample job and you must have displayed it to understand that its not just some random lorem ipsum text but something which was manually written. Oh well, if random text is what you were looking for then here it is: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages and now in this assignment.",
    maxJdSalary: 5,
    minJdSalary: 3,
    salaryCurrencyCode: 'USD',
    location: 'remote',
    minExp: 3,
    maxExp: 12,
    jobRole: 'android',
    companyName: 'Apple',
    logoUrl: 'https://logo.clearbit.com/apple.com',
  },
  {
    jdUid: 'cfff3621-053c-11ef-83d3-06301d0a7178-92028',
    jdLink: 'https://weekday.works',
    jobDetailsFromCompany:
      "This is a sample job and you must have displayed it to understand that its not just some random lorem ipsum text but something which was manually written. Oh well, if random text is what you were looking for then here it is: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages and now in this assignment.",
    maxJdSalary: 33,
    minJdSalary: 23,
    salaryCurrencyCode: 'USD',
    location: 'chennai',
    minExp: 1,
    maxExp: 5,
    jobRole: 'tech lead',
    companyName: 'Asus',
    logoUrl: 'https://logo.clearbit.com/asus.com',
  },
  {
    jdUid: 'cfff362e-053c-11ef-83d3-06301d0a7178-92030',
    jdLink: 'https://weekday.works',
    jobDetailsFromCompany:
      "This is a sample job and you must have displayed it to understand that its not just some random lorem ipsum text but something which was manually written. Oh well, if random text is what you were looking for then here it is: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages and now in this assignment.",
    maxJdSalary: 83,
    minJdSalary: 61,
    salaryCurrencyCode: 'USD',
    location: 'delhi ncr',
    minExp: 6,
    maxExp: 11,
    jobRole: 'frontend',
    companyName: 'Intel Corporation',
    logoUrl: 'https://logo.clearbit.com/intel.com',
  },
];
